apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-claim-serve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-claim-serve
  template:
    metadata:
      labels:
        app: health-claim-serve
    spec:
      containers:
      - name: health-claim-serve-container
        image: <your-registry>/health-claim-serve:v1
        ports:
        - containerPort: 8000